= IndoorGML 1.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies the conformance of the implementation
under test (IUT) with respect to the OGC Indoor GML 1.0 standard. Conformance testing is a kind of "black box" testing that examines the
externally visible characteristics or behaviors of the IUT while disregarding
any implementation details.

The test suite verifies implementations for conformance against the following specification(s):

- http://docs.opengeospatial.org/is/14-005r5/14-005r5.html[OGC® IndoorGML 1.0.3 (14-005r5)] 

Annex A of the specification provides the Abstract Test Suite, detailing the following conformance classes:

A.1 Test Cases for mandatory conformance requirements

- A.1.1 Valid IndoorGML instance document
- A.1.2 Conformance classes related to IndoorGML modules
- A.1.3 Spatial geometry objects


A.2 Conformance classes related to IndoorGML Modules

- A.2.1 IndoorGML Core Module
- A.2.2 IndoorGML Indoor Navigation Module

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. http://docs.opengeospatial.org/is/14-005r5/14-005r5.html[OGC® IndoorGML 1.0.3 (14-005r5)] 



== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.indoorgml10`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Annex A.1 Test Cases for mandatory conformance requirements
|org.opengis.cite.indoorgml10.annexa1.*

|Annex A.2.1 Conformance classes related to IndoorGML Modules - Core Module
|org.opengis.cite.indoorgml10.annexa2_1.*

|Annex A.2.2 Conformance classes related to IndoorGML Modules - Navigation Module
|org.opengis.cite.indoorgml10.annexa2_2.*

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|===
